// apps/svelte-demo/src/components/sl-form-field/sl-form-field.svelte
<script lang="ts">
  import '@sl-design-system/form/register.js';
  import '@sl-design-system/text-field/register.js';
</script>

<div class="states">
  <sl-form-field label="Enabled">
    <sl-text-field></sl-text-field>
  </sl-form-field>

  <sl-form-field label="Disabled">
    <sl-text-field disabled></sl-text-field>
  </sl-form-field>
</div>

// apps/angular-demo/src/app/components/sl-form-field/sl-form-field.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
  FormFieldComponent,
} from '@sl-design-system/angular/form';
import { TextFieldComponent } from '@sl-design-system/angular/text-field';

@Component({
  selector: 'app-form-field-page',
  templateUrl: './sl-form-field.component.html',
  imports: [FormFieldComponent, TextFieldComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class FormFieldPageComponent {}

<div class="states">
  <sl-form-field label="Enabled">
    <sl-text-field></sl-text-field>
  </sl-form-field>

  <sl-form-field label="Disabled">
    <sl-text-field [disabled]="true"></sl-text-field>
  </sl-form-field>
</div>
