// apps/vue-demo/src/components/sl-text-area/sl-text-area.vue
<template>
  <div class="text-area-container">
    <sl-text-area
      aria-label="Text area"
      placeholder="Type your message"
      rows="4"
    ></sl-text-area>
  </div>
</template>

<script setup lang="ts">
import '@sl-design-system/text-area/register.js';
</script>

<style scoped lang="scss" src="./sl-text-area.scss"></style>

// apps/svelte-demo/src/components/sl-text-area/sl-text-area.svelte
<script lang="ts">
  import '@sl-design-system/text-area/register.js';
</script>

<div class="text-area-container">
  <sl-text-area
    aria-label="Text area"
    placeholder="Type your message"
    rows="4"
  ></sl-text-area>
</div>
<div class="text-area-container">
  <sl-text-area
    aria-label="Disabled text area"
    placeholder="Disabled text area"
    rows="4"
    disabled
  ></sl-text-area>
</div>

<style lang="scss" src="./sl-text-area.scss"></style>
