// apps/angular-demo/src/app/components/sl-text-area/sl-text-area.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { TextAreaComponent } from '@sl-design-system/angular/text-area';

@Component({
  selector: 'app-text-area-page',
  templateUrl: './sl-text-area.component.html',
  styleUrls: ['./sl-text-area.component.scss'],
  imports: [TextAreaComponent],
})
export class TextAreaPageComponent {}

<div class="text-area-container">
  <sl-text-area
    aria-label="Text area"
    placeholder="Type your message"
    rows="4"
  ></sl-text-area>
</div>
<div class="text-area-container">
  <sl-text-area
    aria-label="Disabled text area"
    placeholder="Disabled text area"
    rows="4"
    [disabled]="true"
  ></sl-text-area>
</div>

// apps/svelte-demo/src/components/sl-text-area/sl-text-area.svelte
<script lang="ts">
  import '@sl-design-system/text-area/register.js';
</script>

<div class="text-area-container">
  <sl-text-area
    aria-label="Text area"
    placeholder="Type your message"
    rows="4"
  ></sl-text-area>
</div>
<div class="text-area-container">
  <sl-text-area
    aria-label="Disabled text area"
    placeholder="Disabled text area"
    rows="4"
    disabled
  ></sl-text-area>
</div>

<style lang="scss" src="./sl-text-area.scss"></style>
