// apps/vue-demo/src/components/sl-dialog/sl-dialog.vue
<template>
  <sl-button variant="primary" fill="solid" @click="openDialog">Test</sl-button>
  <sl-dialog ref="dialogRef">
    <h1 slot="title">Test title</h1>
    Test description
    <sl-button slot="primary-actions" @click="closeDialog">Close</sl-button>
  </sl-dialog>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import type { Dialog } from '@sl-design-system/dialog';

const dialogRef = ref<Dialog | null>(null);

const openDialog = () => {
  dialogRef.value?.showModal();
};

const closeDialog = () => {
  dialogRef.value?.close();
};
</script>

// apps/angular-demo/src/app/components/sl-dialog.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { ButtonComponent } from '@sl-design-system/angular/button';
import { DialogComponent } from '@sl-design-system/angular/dialog';

@Component({
  selector: 'app-dialog-page',
  template: `
    <sl-button variant="primary" fill="solid" (click)="dialog.elRef.nativeElement.showModal()">Test</sl-button>
    <sl-dialog #dialog>
      <h1 slot="title">Test title</h1>
      Test description
      <sl-button slot="primary-actions" sl-dialog-close>Close</sl-button>
    </sl-dialog>
  `,
  imports: [ButtonComponent, DialogComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class DialogPageComponent {}
