// apps/lit-demo/src/components/sl-accordion/sl-accordion.ts
import { html, LitElement, TemplateResult } from 'lit';
import {
  ScopedElementsMixin,
  type ScopedElementsMap,
} from '@open-wc/scoped-elements/lit-element.js';
import { Accordion, AccordionItem } from '@sl-design-system/accordion';

export class AccordionPage extends ScopedElementsMixin(LitElement) {
  static scopedElements: ScopedElementsMap = {
    'sl-accordion': Accordion,
    'sl-accordion-item': AccordionItem,
  };

  override render(): TemplateResult {
    return html`
      <sl-accordion single>
        <sl-accordion-item summary="Test 1"
          >Extended content for Test 1</sl-accordion-item
        >
        <sl-accordion-item summary="Test 2" disabled
          >Extended content for Test 2</sl-accordion-item
        >
      </sl-accordion>
    `;
  }
}

// apps/angular-demo/src/app/components/sl-accordion/sl-accordion.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
  AccordionComponent,
  AccordionItemComponent,
} from '@sl-design-system/angular/accordion';

@Component({
  selector: 'app-accordion-page',
  templateUrl: './sl-accordion.component.html',
  imports: [AccordionComponent, AccordionItemComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class AccordionPageComponent {}

<sl-accordion single>
  <sl-accordion-item summary="Test 1"
    >Extended content for Test 1</sl-accordion-item
  >
  <sl-accordion-item summary="Test 2" [disabled]="true"
    >Extended content for Test 2</sl-accordion-item
  >
</sl-accordion>
