// apps/vue-demo/src/components/sl-form/sl-form.vue
<template>
  <sl-form>
    <sl-form-field label="Name">
      <sl-text-field name="name" required @sl-change="onNameChange"></sl-text-field>
    </sl-form-field>

    <sl-form-field label="I agree">
      <sl-checkbox name="agree" @sl-change="onAgreeChange"></sl-checkbox>
    </sl-form-field>

    <sl-button-bar>
      <sl-button variant="primary" :disabled="!name || !agreed" @click="onSubmit">Confirm</sl-button>
    </sl-button-bar>
  </sl-form>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import '@sl-design-system/form/register.js';
import '@sl-design-system/text-field/register.js';
import '@sl-design-system/checkbox/register.js';
import '@sl-design-system/button/register.js';
import '@sl-design-system/button-bar/register.js';

const name = ref('');
const agreed = ref(false);

function onNameChange(event: Event) {
  name.value = ((event.target as HTMLElement & { value: string }).value ?? '').trim();
}

function onAgreeChange(event: Event) {
  agreed.value = (event.target as HTMLElement & { checked: boolean }).checked;
}

function onSubmit() {
  window.open('about:blank', '_blank', 'noopener,noreferrer');
}
</script>

// apps/angular-demo/src/app/components/sl-form/sl-form.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { FormComponent, FormFieldComponent } from '@sl-design-system/angular/form';
import { TextFieldComponent } from '@sl-design-system/angular/text-field';
import { CheckboxComponent } from '@sl-design-system/angular/checkbox';
import { ButtonComponent } from '@sl-design-system/angular/button';
import { ButtonBarComponent } from '@sl-design-system/angular/button-bar';

@Component({
  selector: 'app-form-page',
  templateUrl: './sl-form.component.html',
  imports: [FormComponent, FormFieldComponent, TextFieldComponent, CheckboxComponent, ButtonComponent, ButtonBarComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class FormPageComponent {
  name = '';
  agreed = false;

  onNameChange(event: Event): void {
    this.name = ((event.target as HTMLElement & { value: string }).value ?? '').trim();
  }

  onAgreeChange(event: Event): void {
    this.agreed = (event.target as HTMLElement & { checked: boolean }).checked;
  }

  onSubmit(): void {
    window.open('about:blank', '_blank', 'noopener,noreferrer');
  }
}

<sl-form>
  <sl-form-field label="Name">
    <sl-text-field name="name" required (sl-change)="onNameChange($event)"></sl-text-field>
  </sl-form-field>

  <sl-form-field label="I agree">
    <sl-checkbox name="agree" (sl-change)="onAgreeChange($event)"></sl-checkbox>
  </sl-form-field>

  <sl-button-bar>
    <sl-button variant="primary" [disabled]="!name || !agreed" (click)="onSubmit()">Confirm</sl-button>
  </sl-button-bar>
</sl-form>
