// apps/vue-demo/src/components/sl-paginator/sl-paginator.vue
<template>
  <ul>
    <li v-for="item in visibleItems" :key="item.id">
      {{ item.name }}
    </li>
  </ul>
  <sl-paginator-status
    :page="page"
    :page-size="pageSize"
    :total-items="allItems.length"
    item-label="items"
  ></sl-paginator-status>
  <sl-paginator
    ref="paginatorRef"
    :page="page"
    :page-size="pageSize"
    :total-items="allItems.length"
  ></sl-paginator>
  <sl-paginator-page-size
    ref="pageSizeRef"
    :page-size="pageSize"
    item-label="Items"
  ></sl-paginator-page-size>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import {
  Paginator,
  PaginatorPageSize,
  PaginatorStatus,
} from '@sl-design-system/paginator';

if (!customElements.get('sl-paginator'))
  customElements.define('sl-paginator', Paginator);
if (!customElements.get('sl-paginator-page-size'))
  customElements.define('sl-paginator-page-size', PaginatorPageSize);
if (!customElements.get('sl-paginator-status'))
  customElements.define('sl-paginator-status', PaginatorStatus);

import {
  ALL_ITEMS,
  type Item,
} from '../../../../../shared/utils/paginator-items.js';

const allItems: Item[] = ALL_ITEMS;

const page = ref(0);
const pageSize = ref(5);

const visibleItems = computed(() =>
  allItems.slice(
    page.value * pageSize.value,
    page.value * pageSize.value + pageSize.value,
  ),
);

const paginatorRef = ref<Paginator | null>(null);
const pageSizeRef = ref<PaginatorPageSize | null>(null);

function onPageChange(e: Event) {
  page.value = (e as CustomEvent<number>).detail;
}

function onPageSizeChange(e: Event) {
  pageSize.value = (e as CustomEvent<number>).detail;
  page.value = 0;
}

onMounted(() => {
  const pageSizeEl = pageSizeRef.value;
  if (pageSizeEl) {
    pageSizeEl.pageSizes = [5, 10];
    pageSizeEl.addEventListener('sl-page-size-change', onPageSizeChange);
  }

  paginatorRef.value?.addEventListener('sl-page-change', onPageChange);
});
onUnmounted(() => {
  paginatorRef.value?.removeEventListener('sl-page-change', onPageChange);
  pageSizeRef.value?.removeEventListener(
    'sl-page-size-change',
    onPageSizeChange,
  );
});
</script>

// apps/svelte-demo/src/components/sl-paginator/sl-paginator.svelte
<script lang="ts">
  import { Paginator, PaginatorPageSize, PaginatorStatus } from '@sl-design-system/paginator';
  import { ALL_ITEMS, type Item } from '../../../../../shared/utils/paginator-items.js';

  if (!customElements.get('sl-paginator')) customElements.define('sl-paginator', Paginator);
  if (!customElements.get('sl-paginator-page-size')) customElements.define('sl-paginator-page-size', PaginatorPageSize);
  if (!customElements.get('sl-paginator-status')) customElements.define('sl-paginator-status', PaginatorStatus);

  const allItems: Item[] = ALL_ITEMS;

  let page = $state(0);
  let pageSize = $state(5);

  const visibleItems = $derived(allItems.slice(page * pageSize, page * pageSize + pageSize));

  let paginatorEl: HTMLElement | null = $state(null);
  let pageSizeEl: HTMLElement | null = $state(null);

  $effect(() => {
    if (!paginatorEl) return;
    const handler = (e: Event) => {
      page = (e as CustomEvent<number>).detail;
    };
    paginatorEl.addEventListener('sl-page-change', handler);
    return () => paginatorEl?.removeEventListener('sl-page-change', handler);
  });

  $effect(() => {
    if (!pageSizeEl) return;
    const handler = (e: Event) => {
      pageSize = (e as CustomEvent<number>).detail;
      page = 0;
    };
    pageSizeEl.addEventListener('sl-page-size-change', handler);
    return () => pageSizeEl?.removeEventListener('sl-page-size-change', handler);
  });
</script>

<ul>
  {#each visibleItems as item}
    <li>{item.name}</li>
  {/each}
</ul>
<sl-paginator-status
  page={page}
  page-size={pageSize}
  total-items={allItems.length}
  item-label="items"
></sl-paginator-status>
<sl-paginator
  bind:this={paginatorEl}
  page={page}
  page-size={pageSize}
  total-items={allItems.length}
></sl-paginator>
<sl-paginator-page-size
  bind:this={pageSizeEl}
  page-size={pageSize}
  page-sizes={JSON.stringify([5, 10])}
  item-label="Items"
></sl-paginator-page-size>
