// apps/vue-demo/src/components/sl-dialog.vue
<template>
  <sl-button variant="primary" fill="solid" @click="openDialog">Test</sl-button>
  <sl-dialog ref="dialogRef">
    <h1 slot="title">Test title</h1>
    Test description
    <sl-button slot="primary-actions" sl-dialog-close>Close</sl-button>
  </sl-dialog>
</template>

<script setup lang="ts">
import { ref } from 'vue';

const dialogRef = ref<HTMLElement | null>(null);

const openDialog = () => {
  (dialogRef.value as any)?.showModal();
};
</script>

// apps/svelte-demo/src/components/sl-dialog/sl-dialog.svelte
<script lang="ts">
  let dialogEl: HTMLElement;

  function openDialog() {
    (dialogEl as any).showModal();
  }
</script>

<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
<sl-button variant="primary" fill="solid" onclick={openDialog}>Test</sl-button>
<sl-dialog bind:this={dialogEl}>
  <h1 slot="title">Test title</h1>
  Test description
  <sl-button slot="primary-actions" sl-dialog-close>Close</sl-button>
</sl-dialog>
