// apps/svelte-demo/src/components/sl-tag/sl-tag.svelte
<script lang="ts">
  import '@sl-design-system/tag/register.js';
</script>

 <style lang="scss" src="./sl-tag.scss"></style>

<sl-tag-list class="tags" aria-label="Subjects">
  <sl-tag removable>Mathematics</sl-tag>
  <sl-tag removable>Physics</sl-tag>
  <sl-tag disabled=${true} removable>Chemistry</sl-tag>
</sl-tag-list>

// apps/vue-demo/src/components/sl-tag/sl-tag.vue
<template>
  <sl-tag-list class="tags" aria-label="Subjects">
    <sl-tag removable="true">Mathematics</sl-tag>
    <sl-tag removable="true">Physics</sl-tag>
    <sl-tag :disabled="true" removable="true">Chemistry</sl-tag>
  </sl-tag-list>
</template>

<style scoped lang="scss">
@use './sl-tag.scss';
</style>

<script setup lang="ts">
import '@sl-design-system/tag/register.js';
</script>
