// apps/vue-demo/src/components/sl-message-dialog/sl-message-dialog.vue
<template>
  <sl-button variant="primary" fill="solid" @click="showAlert">Show</sl-button>
</template>

<script setup lang="ts">
import { MessageDialog } from '@sl-design-system/message-dialog';
import '@sl-design-system/message-dialog/register.js';

const showAlert = async () => {
  await MessageDialog.alert('Test description', 'Test');
};
</script>

// apps/angular-demo/src/app/components/sl-message-dialog/sl-message-dialog.component.ts
import { Component } from '@angular/core';
import { MessageDialog } from '@sl-design-system/message-dialog';
import '@sl-design-system/message-dialog/register.js';
import { ButtonComponent } from '@sl-design-system/angular/button';

@Component({
  selector: 'app-message-dialog-page',
  templateUrl: './sl-message-dialog.component.html',
  imports: [ButtonComponent],
})
export class MessageDialogPageComponent {
  showAlert(): void {
    void MessageDialog.alert('Test description', 'Test');
  }
}

<sl-button variant="primary" fill="solid" (click)="showAlert()">Show</sl-button>
