// apps/lit-demo/src/components/sl-toggle-button/sl-toggle-button.ts
import { html, LitElement, TemplateResult } from 'lit';
import {
  ScopedElementsMixin,
  type ScopedElementsMap,
} from '@open-wc/scoped-elements/lit-element.js';
import { ToggleButton } from '@sl-design-system/toggle-button';

export class ToggleButtonPage extends ScopedElementsMixin(LitElement) {
  static scopedElements: ScopedElementsMap = {
    'sl-toggle-button': ToggleButton,
  };

  override render(): TemplateResult {
    return html`
      <sl-toggle-button variant="primary" fill="solid">Test 1</sl-toggle-button>
      <sl-toggle-button variant="primary" fill="solid" disabled
        >Test 2</sl-toggle-button
      >
    `;
  }
}

// apps/angular-demo/src/app/components/sl-toggle-button/sl-toggle-button.component.ts
import { Component } from '@angular/core';
import { ToggleButtonComponent } from '@sl-design-system/angular/toggle-button';

@Component({
  selector: 'app-toggle-button-page',
  templateUrl: './sl-toggle-button.component.html',
  styleUrls: ['./sl-toggle-button.component.scss'],
  imports: [ToggleButtonComponent],
})
export class ToggleButtonPageComponent {}

<sl-toggle-button variant="primary" fill="solid">Test 1</sl-toggle-button>
<sl-toggle-button variant="primary" fill="solid" [disabled]="true"
  >Test 2</sl-toggle-button
>
