// apps/angular-demo/src/app/components/sl-switch/sl-switch.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import '@sl-design-system/switch/register.js';

@Component({
  selector: 'app-switch-page',
  templateUrl: './sl-switch.component.html',
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class SwitchPageComponent {}
<div style="display: flex; flex-direction: column; gap: 0.75rem; align-items: flex-start;">
  <sl-switch value="12345">Text inside the switch</sl-switch>
  <sl-switch value="12345" [disabled]="true">Disabled switch</sl-switch>
</div>

// apps/vue-demo/src/components/sl-switch/sl-switch.vue
<template>
  <div
    style="
      display: flex;
      flex-direction: column;
      gap: 0.75rem;
      align-items: flex-start;
    "
  >
    <sl-switch value="12345">Text inside the switch</sl-switch>
    <sl-switch value="12345" :disabled="true">Disabled switch</sl-switch>
  </div>
</template>
