// apps/angular-demo/src/app/components/sl-button.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { ButtonComponent } from '@sl-design-system/angular/button';

@Component({
  selector: 'app-button-page',
  template: `
    <sl-button variant="info" size="lg" (click)="openBlankPage()"
      >Button</sl-button
    >
  `,
  imports: [ButtonComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class ButtonPageComponent {
  openBlankPage() {
    window.open('about:blank', '_blank', 'noopener,noreferrer');
  }
}

// apps/svelte-demo/src/components/sl-button.svelte
<script lang="ts">
  function openBlankPage() {
    window.open('about:blank', '_blank', 'noopener,noreferrer');
  }
</script>

<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
<sl-button variant="info" size="lg" onclick={openBlankPage}>Button</sl-button>
