// apps/angular-demo/src/app/components/sl-inline-message/sl-inline-message.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { InlineMessageComponent } from '@sl-design-system/angular/inline-message';

@Component({
  selector: 'app-inline-message-page',
  templateUrl: './sl-inline-message.component.html',
  imports: [InlineMessageComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class InlineMessagePageComponent {}

<sl-inline-message variant="success">
  <span slot="title">Test</span>
  Test description
</sl-inline-message>

// apps/lit-demo/src/components/sl-inline-message/sl-inline-message.ts
import { html, LitElement, TemplateResult } from 'lit';
import {
  ScopedElementsMixin,
  type ScopedElementsMap,
} from '@open-wc/scoped-elements/lit-element.js';
import { InlineMessage } from '@sl-design-system/inline-message';

export class InlineMessagePage extends ScopedElementsMixin(LitElement) {
  static scopedElements: ScopedElementsMap = {
    'sl-inline-message': InlineMessage,
  };

  override render(): TemplateResult {
    return html`
      <sl-inline-message variant="success">
        <span slot="title">Test</span>
        Test description
      </sl-inline-message>
    `;
  }
}
