// apps/vue-demo/src/components/sl-callout/sl-callout.vue
<template>
  <sl-callout variant="info">
    <h2 slot="title">Test title</h2>
    Test description.
    <a href="about:blank" target="_blank" rel="noopener noreferrer"
      >Open link</a
    >
    <sl-button fill="outline" variant="info" @click="openBlankPage"
      >Open page</sl-button
    >
  </sl-callout>
</template>

<script setup lang="ts">
const openBlankPage = () => {
  window.open('about:blank', '_blank', 'noopener,noreferrer');
};
</script>

// apps/angular-demo/src/app/components/sl-callout/sl-callout.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { ButtonComponent } from '@sl-design-system/angular/button';

@Component({
  selector: 'app-callout-page',
  templateUrl: './sl-callout.component.html',
  imports: [ButtonComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class CalloutPageComponent {
  openBlankPage() {
    window.open('about:blank', '_blank', 'noopener,noreferrer');
  }
}

<sl-callout variant="info">
  <h2 slot="title">Test title</h2>
  Test description.
  <a href="about:blank" target="_blank" rel="noopener noreferrer">Open link</a>
  <sl-button fill="outline" variant="info" (click)="openBlankPage()"
    >Open page</sl-button
  >
</sl-callout>
