// apps/lit-demo/src/app/app.ts
import { html, LitElement, TemplateResult } from 'lit';
import { state } from 'lit/decorators.js';
import {
  ScopedElementsMixin,
  type ScopedElementsMap,
} from '@open-wc/scoped-elements/lit-element.js';
import { AccordionPage } from '../components/sl-accordion/sl-accordion.js';
import { AvatarPage } from '../components/sl-avatar/sl-avatar.js';
import { BreadcrumbsPage } from '../components/sl-breadcrumbs/sl-breadcrumbs.js';
import { ButtonPage } from '../components/sl-button/sl-button.js';
import { ButtonBarPage } from '../components/sl-button-bar/sl-button-bar.js';
import { CalloutPage } from '../components/sl-callout/sl-callout.js';
import { CheckboxPage } from '../components/sl-checkbox/sl-checkbox.js';
import { ComboboxPage } from '../components/sl-combobox/sl-combobox.js';
import { DialogPage } from '../components/sl-dialog/sl-dialog.js';
import { FormFieldPage } from '../components/sl-form-field/sl-form-field.js';
import { FormPage } from '../components/sl-form/sl-form.js';
import { InlineMessagePage } from '../components/sl-inline-message/sl-inline-message.js';
import { MenuPage } from '../components/sl-menu/sl-menu.js';
import { MessageDialogPage } from '../components/sl-message-dialog/sl-message-dialog.js';
import { NumberFieldPage } from '../components/sl-number-field/sl-number-field.js';
import { TextAreaPage } from '../components/sl-text-area/sl-text-area.js';
import { TabGroupPage } from '../components/sl-tab-group/sl-tab-group.js';
import { PaginatorPage } from '../components/sl-paginator/sl-paginator.js';
import { SelectPage } from '../components/sl-select/sl-select.js';
import { SwitchPage } from '../components/sl-switch/sl-switch.js';
import { CardPage } from '../components/sl-card/sl-card.js';
import { PopoverPage } from '../components/sl-popover/sl-popover.js';
import { TooltipPage } from '../components/sl-tooltip/sl-tooltip.js';
import { RadioGroupPage } from '../components/sl-radio-group/sl-radio-group.js';
import { ToggleButtonPage } from '../components/sl-toggle-button/sl-toggle-button.js';
import styles from './app.styles.scss.js';

const ROUTES = [
  { path: '/sl-accordion', label: 'sl-accordion' },
  { path: '/sl-avatar', label: 'sl-avatar' },
  { path: '/sl-breadcrumbs', label: 'sl-breadcrumbs' },
  { path: '/sl-button', label: 'sl-button' },
  { path: '/sl-button-bar', label: 'sl-button-bar' },
  { path: '/sl-callout', label: 'sl-callout' },
  { path: '/sl-checkbox', label: 'sl-checkbox' },
  { path: '/sl-combobox', label: 'sl-combobox' },
  { path: '/sl-dialog', label: 'sl-dialog' },
  { path: '/sl-form-field', label: 'sl-form-field' },
  { path: '/sl-form', label: 'sl-form' },
  { path: '/sl-inline-message', label: 'sl-inline-message' },
  { path: '/sl-menu', label: 'sl-menu' },
  { path: '/sl-message-dialog', label: 'sl-message-dialog' },
  { path: '/sl-number-field', label: 'sl-number-field' },
  { path: '/sl-text-area', label: 'sl-text-area' },
  { path: '/sl-tab-group', label: 'sl-tab-group' },
  { path: '/sl-paginator', label: 'sl-paginator' },
  { path: '/sl-select', label: 'sl-select' },
  { path: '/sl-switch', label: 'sl-switch' },
  { path: '/sl-card', label: 'sl-card' },
  { path: '/sl-popover', label: 'sl-popover' },
  { path: '/sl-toggle-button', label: 'sl-toggle-button' },
  { path: '/sl-tooltip', label: 'sl-tooltip' },
  { path: '/sl-radio-group', label: 'sl-radio-group' },
];

export class App extends ScopedElementsMixin(LitElement) {
  static scopedElements: ScopedElementsMap = {
    'page-accordion': AccordionPage,
    'page-avatar': AvatarPage,
    'page-breadcrumbs': BreadcrumbsPage,
    'page-button': ButtonPage,
    'page-button-bar': ButtonBarPage,
    'page-callout': CalloutPage,
    'page-checkbox': CheckboxPage,
    'page-combobox': ComboboxPage,
    'page-dialog': DialogPage,
    'page-form-field': FormFieldPage,
    'page-form': FormPage,
    'page-inline-message': InlineMessagePage,
    'page-menu': MenuPage,
    'page-message-dialog': MessageDialogPage,
    'page-number-field': NumberFieldPage,
    'page-text-area': TextAreaPage,
    'page-tab-group': TabGroupPage,
    'page-paginator': PaginatorPage,
    'page-select': SelectPage,
    'page-switch': SwitchPage,
    'page-card': CardPage,
    'page-popover': PopoverPage,
    'page-toggle-button': ToggleButtonPage,
    'page-tooltip': TooltipPage,
    'page-radio-group': RadioGroupPage,
  };

  static override styles = styles;

  @state() private _currentPath = window.location.pathname;
  @state() private _navCollapsed = false;

  private _onPopState = () => {
    this._currentPath = window.location.pathname;
  };

  override connectedCallback(): void {
    super.connectedCallback();
    window.addEventListener('popstate', this._onPopState);
    if (this._currentPath === '/') {
      this._navigate('/sl-accordion');
    }
  }

  override disconnectedCallback(): void {
    super.disconnectedCallback();
    window.removeEventListener('popstate', this._onPopState);
  }

  private _navigate(path: string): void {
    window.history.pushState(null, '', path);
    this._currentPath = path;
  }

  private _renderPage(): TemplateResult {
    switch (this._currentPath) {
      case '/sl-accordion':
        return html`<page-accordion></page-accordion>`;
      case '/sl-avatar':
        return html`<page-avatar></page-avatar>`;
      case '/sl-breadcrumbs':
        return html`<page-breadcrumbs></page-breadcrumbs>`;
      case '/sl-button':
        return html`<page-button></page-button>`;
      case '/sl-button-bar':
        return html`<page-button-bar></page-button-bar>`;
      case '/sl-callout':
        return html`<page-callout></page-callout>`;
      case '/sl-checkbox':
        return html`<page-checkbox></page-checkbox>`;
      case '/sl-combobox':
        return html`<page-combobox></page-combobox>`;
      case '/sl-dialog':
        return html`<page-dialog></page-dialog>`;
      case '/sl-form-field':
        return html`<page-form-field></page-form-field>`;
      case '/sl-form':
        return html`<page-form></page-form>`;
      case '/sl-inline-message':
        return html`<page-inline-message></page-inline-message>`;
      case '/sl-menu':
        return html`<page-menu></page-menu>`;
      case '/sl-message-dialog':
        return html`<page-message-dialog></page-message-dialog>`;
      case '/sl-number-field':
        return html`<page-number-field></page-number-field>`;
      case '/sl-text-area':
        return html`<page-text-area></page-text-area>`;
      case '/sl-tab-group':
        return html`<page-tab-group></page-tab-group>`;
      case '/sl-paginator':
        return html`<page-paginator></page-paginator>`;
      case '/sl-select':
        return html`<page-select></page-select>`;
      case '/sl-switch':
        return html`<page-switch></page-switch>`;
      case '/sl-card':
        return html`<page-card></page-card>`;
      case '/sl-popover':
        return html`<page-popover></page-popover>`;
      case '/sl-toggle-button':
        return html`<page-toggle-button></page-toggle-button>`;
      case '/sl-tooltip':
        return html`<page-tooltip></page-tooltip>`;
      case '/sl-radio-group':
        return html`<page-radio-group></page-radio-group>`;
      default:
        return html``;
    }
  }

  override render(): TemplateResult {
    return html`
      <div class="app-layout">
        <a href="#main" class="skip-link">Skip to main content</a>
        <nav
          class="sidebar ${this._navCollapsed ? 'collapsed' : ''}"
          aria-label="Main navigation"
          id="app-sidebar"
        >
          <button
            class="sidebar-toggle"
            aria-controls="app-sidebar"
            @click=${() => (this._navCollapsed = !this._navCollapsed)}
            aria-expanded="${!this._navCollapsed}"
            title="Toggle navigation"
          >
            <span aria-hidden="true">☰</span>
            <span class="visually-hidden"
              >${this._navCollapsed
                ? 'Expand navigation'
                : 'Collapse navigation'}</span
            >
          </button>
          <h2>Lit Demo App</h2>
          <ul class="sidebar-list">
            ${ROUTES.map(
              ({ path, label }) => html`
                <li>
                  <a
                    href=${path}
                    class=${this._currentPath === path ? 'active' : ''}
                    @click=${(e: Event) => {
                      e.preventDefault();
                      this._navigate(path);
                    }}
                    ><span class="label">${label}</span></a
                  >
                </li>
              `,
            )}
          </ul>
        </nav>
        <main id="main" class="content" tabindex="-1">
          ${this._renderPage()}
        </main>
      </div>
    `;
  }
}

customElements.define('demo-app', App);

// apps/svelte-demo/src/App.svelte
<script lang="ts">
  import Accordion from './components/sl-accordion/sl-accordion.svelte';
  import Avatar from './components/sl-avatar/sl-avatar.svelte';
  import Breadcrumbs from './components/sl-breadcrumbs/sl-breadcrumbs.svelte';
  import Button from './components/sl-button/sl-button.svelte';
  import ButtonBar from './components/sl-button-bar/sl-button-bar.svelte';
  import Callout from './components/sl-callout/sl-callout.svelte';
  import Checkbox from './components/sl-checkbox/sl-checkbox.svelte';
  import Combobox from './components/sl-combobox/sl-combobox.svelte';
  import Dialog from './components/sl-dialog/sl-dialog.svelte';
  import FormField from './components/sl-form-field/sl-form-field.svelte';
  import Form from './components/sl-form/sl-form.svelte';
  import InlineMessage from './components/sl-inline-message/sl-inline-message.svelte';
  import Link from './components/sl-link/sl-link.svelte';
  import Menu from './components/sl-menu/sl-menu.svelte';
  import RadioGroup from './components/sl-radio-group/sl-radio-group.svelte';
  import MessageDialog from './components/sl-message-dialog/sl-message-dialog.svelte';
  import NumberField from './components/sl-number-field/sl-number-field.svelte';
  import TextArea from './components/sl-text-area/sl-text-area.svelte';
  import TabGroup from './components/sl-tab-group/sl-tab-group.svelte';
  import Paginator from './components/sl-paginator/sl-paginator.svelte';
  import Select from './components/sl-select/sl-select.svelte';
  import Switch from './components/sl-switch/sl-switch.svelte';
  import Card from './components/sl-card/sl-card.svelte';
  import Popover from './components/sl-popover/sl-popover.svelte';
  import ToggleButton from './components/sl-toggle-button/sl-toggle-button.svelte';
  import Tooltip from './components/sl-tooltip/sl-tooltip.svelte';

  const navItems = [
    { path: '/sl-accordion', label: 'sl-accordion', component: Accordion },
    { path: '/sl-avatar', label: 'sl-avatar', component: Avatar },
    { path: '/sl-breadcrumbs', label: 'sl-breadcrumbs', component: Breadcrumbs },
    { path: '/sl-button', label: 'sl-button', component: Button },
    { path: '/sl-button-bar', label: 'sl-button-bar', component: ButtonBar },
    { path: '/sl-callout', label: 'sl-callout', component: Callout },
    { path: '/sl-checkbox', label: 'sl-checkbox', component: Checkbox },
    { path: '/sl-combobox', label: 'sl-combobox', component: Combobox },
    { path: '/sl-dialog', label: 'sl-dialog', component: Dialog },
    { path: '/sl-form-field', label: 'sl-form-field', component: FormField },
    { path: '/sl-form', label: 'sl-form', component: Form },
    { path: '/sl-inline-message', label: 'sl-inline-message', component: InlineMessage },
    { path: '/sl-link', label: 'sl-link', component: Link },
    { path: '/sl-menu', label: 'sl-menu', component: Menu },
    { path: '/sl-message-dialog', label: 'sl-message-dialog', component: MessageDialog },
    { path: '/sl-number-field', label: 'sl-number-field', component: NumberField },
    { path: '/sl-text-area', label: 'sl-text-area', component: TextArea },
    { path: '/sl-tab-group', label: 'sl-tab-group', component: TabGroup },
    { path: '/sl-paginator', label: 'sl-paginator', component: Paginator },
    { path: '/sl-select', label: 'sl-select', component: Select },
    { path: '/sl-switch', label: 'sl-switch', component: Switch },
    { path: '/sl-card', label: 'sl-card', component: Card },
    { path: '/sl-popover', label: 'sl-popover', component: Popover },
    { path: '/sl-toggle-button', label: 'sl-toggle-button', component: ToggleButton },
    { path: '/sl-tooltip', label: 'sl-tooltip', component: Tooltip },
    { path: '/sl-radio-group', label: 'sl-radio-group', component: RadioGroup },
  ];

  const initialPath = window.location.pathname === '/' ? '/sl-accordion' : window.location.pathname;
  if (window.location.pathname === '/') {
    window.history.replaceState(null, '', '/sl-accordion');
  }
  let currentPath = $state(initialPath);
  let navCollapsed = $state(false);

  const CurrentPage = $derived(
    navItems.find((item) => item.path === currentPath)?.component ?? Accordion
  );

  function navigate(path: string) {
    window.history.pushState(null, '', path);
    currentPath = path;
  }

  $effect(() => {
    const onPopState = () => { currentPath = window.location.pathname; };
    window.addEventListener('popstate', onPopState);
    return () => window.removeEventListener('popstate', onPopState);
  });
</script>

  <div class="app-layout">
  <a href="#main" class="skip-link">Skip to main content</a>
  <nav class="sidebar" class:collapsed={navCollapsed} aria-label="Main navigation" id="app-sidebar">
    <button
      class="sidebar-toggle"
      aria-controls="app-sidebar"
      onclick={() => (navCollapsed = !navCollapsed)}
      aria-expanded={!navCollapsed}
      title="Toggle navigation"
    >
      <span aria-hidden="true">☰</span>
      <span class="visually-hidden">{navCollapsed ? 'Expand navigation' : 'Collapse navigation'}</span>
    </button>
    <h2>Svelte Demo App</h2>
    <ul class="sidebar-list">
      {#each navItems as item}
        <li>
          <a
            href={item.path}
            class:active={currentPath === item.path}
            onclick={(e) => { e.preventDefault(); navigate(item.path); }}
          ><span class="label">{item.label}</span></a>
        </li>
      {/each}
    </ul>
  </nav>
  <main id="main" class="content" tabindex="-1">
    <CurrentPage />
  </main>
</div>
