// apps/angular-demo/src/app/app.component.ts
import { Component } from '@angular/core';
import { RouterLink, RouterLinkActive, RouterOutlet } from '@angular/router';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  imports: [RouterOutlet, RouterLink, RouterLinkActive],
  styleUrls: ['./app.component.scss'],
})
export class AppComponent {
  navItems = [
    { path: 'sl-avatar', label: 'sl-avatar' },
    { path: 'sl-accordion', label: 'sl-accordion' },
    { path: 'sl-breadcrumbs', label: 'sl-breadcrumbs' },
    { path: 'sl-button', label: 'sl-button' },
    { path: 'sl-button-bar', label: 'sl-button-bar' },
    { path: 'sl-callout', label: 'sl-callout' },
    { path: 'sl-card', label: 'sl-card' },
    { path: 'sl-checkbox', label: 'sl-checkbox' },
    { path: 'sl-combobox', label: 'sl-combobox' },
    { path: 'sl-dialog', label: 'sl-dialog' },
    { path: 'sl-dialog-service', label: 'sl-dialog-service' },
    { path: 'sl-form-field', label: 'sl-form-field' },
    { path: 'sl-form-reactive', label: 'sl-form (reactive)' },
    { path: 'sl-form-template', label: 'sl-form (template)' },
    { path: 'sl-inline-message', label: 'sl-inline-message' },
    { path: 'sl-menu', label: 'sl-menu' },
    { path: 'sl-message-dialog', label: 'sl-message-dialog' },
    { path: 'sl-message-dialog-service', label: 'sl-message-dialog-service' },
    { path: 'sl-number-field', label: 'sl-number-field' },
    { path: 'sl-text-area', label: 'sl-text-area' },
    { path: 'sl-tab-group', label: 'sl-tab-group' },
    { path: 'sl-paginator', label: 'sl-paginator' },
    { path: 'sl-select', label: 'sl-select' },
    { path: 'sl-switch', label: 'sl-switch' },
    { path: 'sl-popover', label: 'sl-popover' },
    { path: 'sl-toggle-button', label: 'sl-toggle-button' },
    { path: 'sl-toggle-group', label: 'sl-toggle-group' },
    { path: 'sl-tooltip', label: 'sl-tooltip' },
    { path: 'sl-radio-group-reactive', label: 'sl-radio-group (reactive)' },
    { path: 'sl-radio-group-template', label: 'sl-radio-group (template)' },
  ];

  // simple collapsed state for nav toggle in template
  navCollapsed = false;
}

<h1>Hello Angular Demo!</h1>

<h2>Nav Item Component (Button Style)</h2>
<nav style="margin-bottom: 2rem;">
  <app-nav-item [ariaDescribedby]="'test123'" label="Home" href="/home" [isActive]="true"></app-nav-item>
  <sl-tooltip id="test123">Navigate to Home</sl-tooltip>
  <app-nav-item [ariaDescribedby]="'test123a'" label="About" href="/about"></app-nav-item>
  <sl-tooltip id="test123a">Navigate to Home</sl-tooltip>
  <app-nav-item [ariaDescribedby]="'test123b'" label="Services" href="/services"></app-nav-item>
  <sl-tooltip id="test123b">Navigate to Home</sl-tooltip>
  <app-nav-item [ariaDescribedby]="'test123c'" label="Contact" href="/contact"></app-nav-item>
  <sl-tooltip id="test123c">Navigate to Home</sl-tooltip>
</nav>

<h2>Nav Link Component (Underline Style) - With Tooltip Directive</h2>
<nav style="margin-bottom: 2rem;">
  <app-nav-link label="Home" href="/home" [isActive]="true" [tooltipText]="'Home Page'"></app-nav-link>
  <app-nav-link label="Products" href="/products"  [tooltipText]="'Products Page'"></app-nav-link>
  <app-nav-link label="Blog" href="/blog"  [tooltipText]="'Blog Page'"></app-nav-link>
  <app-nav-link label="Contact" href="/contact"  [tooltipText]="'Contact Page'"></app-nav-link>
</nav>

<div class="buttons-wrapper">
<sl-button variant="info" size="lg" aria-describedby="my-tooltip">Button</sl-button>
<sl-tooltip id="my-tooltip">
  This is a tooltip
</sl-tooltip>

<sl-button variant="info" size="lg" [attr.aria-describedby]="`my-tooltip2`">Button</sl-button>
<sl-tooltip [id]="`my-tooltip2`">
  This is a tooltip
</sl-tooltip>

<sl-button variant="info" size="lg" slTooltip="I am a tooltip added via directive to the button">Button</sl-button>

</div>

<div class="links-wrapper">
  <a href="https://angular.io/guide/component-overview" target="_blank" class="card-link" aria-describedby="my-tooltip-link">
    Read More with tooltip component →
  </a>
  <sl-tooltip id="my-tooltip-link">
    Link tooltip added via tooltip component
  </sl-tooltip>
</div>

<div class="links-wrapper">
  <a [slTooltip]="tooltipText" href="https://angular.io/guide/component-overview" target="_blank" class="card-link">
    Read More with tooltip directive →
  </a>
</div>

// apps/svelte-demo/src/App.svelte
<script lang="ts">
  import Accordion from './components/sl-accordion/sl-accordion.svelte';
  import Avatar from './components/sl-avatar/sl-avatar.svelte';
  import Breadcrumbs from './components/sl-breadcrumbs/sl-breadcrumbs.svelte';
  import Button from './components/sl-button/sl-button.svelte';
  import ButtonBar from './components/sl-button-bar/sl-button-bar.svelte';
  import Callout from './components/sl-callout/sl-callout.svelte';
  import Checkbox from './components/sl-checkbox/sl-checkbox.svelte';
  import Combobox from './components/sl-combobox/sl-combobox.svelte';
  import Dialog from './components/sl-dialog/sl-dialog.svelte';
  import FormField from './components/sl-form-field/sl-form-field.svelte';
  import Form from './components/sl-form/sl-form.svelte';
  import InlineMessage from './components/sl-inline-message/sl-inline-message.svelte';
  import Link from './components/sl-link/sl-link.svelte';
  import Menu from './components/sl-menu/sl-menu.svelte';
  import RadioGroup from './components/sl-radio-group/sl-radio-group.svelte';
  import MessageDialog from './components/sl-message-dialog/sl-message-dialog.svelte';
  import NumberField from './components/sl-number-field/sl-number-field.svelte';
  import TextArea from './components/sl-text-area/sl-text-area.svelte';
  import TabGroup from './components/sl-tab-group/sl-tab-group.svelte';
  import Paginator from './components/sl-paginator/sl-paginator.svelte';
  import Select from './components/sl-select/sl-select.svelte';
  import Switch from './components/sl-switch/sl-switch.svelte';
  import Card from './components/sl-card/sl-card.svelte';
  import Popover from './components/sl-popover/sl-popover.svelte';
  import ToggleButton from './components/sl-toggle-button/sl-toggle-button.svelte';
  import Tooltip from './components/sl-tooltip/sl-tooltip.svelte';

  const navItems = [
    { path: '/sl-accordion', label: 'sl-accordion', component: Accordion },
    { path: '/sl-avatar', label: 'sl-avatar', component: Avatar },
    { path: '/sl-breadcrumbs', label: 'sl-breadcrumbs', component: Breadcrumbs },
    { path: '/sl-button', label: 'sl-button', component: Button },
    { path: '/sl-button-bar', label: 'sl-button-bar', component: ButtonBar },
    { path: '/sl-callout', label: 'sl-callout', component: Callout },
    { path: '/sl-checkbox', label: 'sl-checkbox', component: Checkbox },
    { path: '/sl-combobox', label: 'sl-combobox', component: Combobox },
    { path: '/sl-dialog', label: 'sl-dialog', component: Dialog },
    { path: '/sl-form-field', label: 'sl-form-field', component: FormField },
    { path: '/sl-form', label: 'sl-form', component: Form },
    { path: '/sl-inline-message', label: 'sl-inline-message', component: InlineMessage },
    { path: '/sl-link', label: 'sl-link', component: Link },
    { path: '/sl-menu', label: 'sl-menu', component: Menu },
    { path: '/sl-message-dialog', label: 'sl-message-dialog', component: MessageDialog },
    { path: '/sl-number-field', label: 'sl-number-field', component: NumberField },
    { path: '/sl-text-area', label: 'sl-text-area', component: TextArea },
    { path: '/sl-tab-group', label: 'sl-tab-group', component: TabGroup },
    { path: '/sl-paginator', label: 'sl-paginator', component: Paginator },
    { path: '/sl-select', label: 'sl-select', component: Select },
    { path: '/sl-switch', label: 'sl-switch', component: Switch },
    { path: '/sl-card', label: 'sl-card', component: Card },
    { path: '/sl-popover', label: 'sl-popover', component: Popover },
    { path: '/sl-toggle-button', label: 'sl-toggle-button', component: ToggleButton },
    { path: '/sl-tooltip', label: 'sl-tooltip', component: Tooltip },
    { path: '/sl-radio-group', label: 'sl-radio-group', component: RadioGroup },
  ];

  const initialPath = window.location.pathname === '/' ? '/sl-accordion' : window.location.pathname;
  if (window.location.pathname === '/') {
    window.history.replaceState(null, '', '/sl-accordion');
  }
  let currentPath = $state(initialPath);
  let navCollapsed = $state(false);

  const CurrentPage = $derived(
    navItems.find((item) => item.path === currentPath)?.component ?? Accordion
  );

  function navigate(path: string) {
    window.history.pushState(null, '', path);
    currentPath = path;
  }

  $effect(() => {
    const onPopState = () => { currentPath = window.location.pathname; };
    window.addEventListener('popstate', onPopState);
    return () => window.removeEventListener('popstate', onPopState);
  });
</script>

  <div class="app-layout">
  <a href="#main" class="skip-link">Skip to main content</a>
  <nav class="sidebar" class:collapsed={navCollapsed} aria-label="Main navigation" id="app-sidebar">
    <button
      class="sidebar-toggle"
      aria-controls="app-sidebar"
      onclick={() => (navCollapsed = !navCollapsed)}
      aria-expanded={!navCollapsed}
      title="Toggle navigation"
    >
      <span aria-hidden="true">☰</span>
      <span class="visually-hidden">{navCollapsed ? 'Expand navigation' : 'Collapse navigation'}</span>
    </button>
    <h2>Svelte Demo App</h2>
    <ul class="sidebar-list">
      {#each navItems as item}
        <li>
          <a
            href={item.path}
            class:active={currentPath === item.path}
            onclick={(e) => { e.preventDefault(); navigate(item.path); }}
          ><span class="label">{item.label}</span></a>
        </li>
      {/each}
    </ul>
  </nav>
  <main id="main" class="content" tabindex="-1">
    <CurrentPage />
  </main>
</div>
