// apps/angular-demo/src/app/components/sl-checkbox/sl-checkbox.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
  CheckboxComponent,
  CheckboxGroupComponent,
} from '@sl-design-system/angular/checkbox';

@Component({
  selector: 'app-checkbox-page',
  templateUrl: './sl-checkbox.component.html',
  imports: [CheckboxComponent, CheckboxGroupComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class CheckboxPageComponent {}

<sl-checkbox-group>
  <sl-checkbox value="enabled">Test 1</sl-checkbox>
  <sl-checkbox value="disabled" [disabled]="true">Test 2</sl-checkbox>
</sl-checkbox-group>

// apps/lit-demo/src/components/sl-checkbox/sl-checkbox.ts
import { html, LitElement, TemplateResult } from 'lit';
import {
  ScopedElementsMixin,
  type ScopedElementsMap,
} from '@open-wc/scoped-elements/lit-element.js';
import { Checkbox, CheckboxGroup } from '@sl-design-system/checkbox';

export class CheckboxPage extends ScopedElementsMixin(LitElement) {
  static scopedElements: ScopedElementsMap = {
    'sl-checkbox': Checkbox,
    'sl-checkbox-group': CheckboxGroup,
  };

  override render(): TemplateResult {
    return html`
      <sl-checkbox-group>
        <sl-checkbox value="enabled">Test 1</sl-checkbox>
        <sl-checkbox value="disabled" disabled>Test 2</sl-checkbox>
      </sl-checkbox-group>
    `;
  }
}
