// apps/angular-demo/src/app/components/sl-number-field/sl-number-field.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { NumberFieldComponent } from '@sl-design-system/angular/number-field';

@Component({
  selector: 'app-number-field-page',
  templateUrl: './sl-number-field.component.html',
  imports: [NumberFieldComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class NumberFieldPageComponent {}

<sl-number-field
  aria-label="Number field"
  value="1"
  step-buttons="end"
></sl-number-field>

// apps/lit-demo/src/components/sl-number-field/sl-number-field.ts
import { html, LitElement, TemplateResult } from 'lit';
import {
  ScopedElementsMixin,
  type ScopedElementsMap,
} from '@open-wc/scoped-elements/lit-element.js';
import { NumberField } from '@sl-design-system/number-field';

export class NumberFieldPage extends ScopedElementsMixin(LitElement) {
  static scopedElements: ScopedElementsMap = {
    'sl-number-field': NumberField,
  };

  override render(): TemplateResult {
    return html`
      <sl-number-field
        aria-label="Number field"
        value="1"
        step-buttons="end"
      ></sl-number-field>
    `;
  }
}
