// apps/lit-demo/src/components/sl-radio-group/sl-radio-group.ts
import { html, LitElement, TemplateResult } from 'lit';
import {
  ScopedElementsMixin,
  type ScopedElementsMap,
} from '@open-wc/scoped-elements/lit-element.js';
import { Button } from '@sl-design-system/button';
import { ButtonBar } from '@sl-design-system/button-bar';
import { Form, FormField } from '@sl-design-system/form';
import { Radio, RadioGroup } from '@sl-design-system/radio-group';

export class RadioGroupPage extends ScopedElementsMixin(LitElement) {
  static scopedElements: ScopedElementsMap = {
    'sl-button': Button,
    'sl-button-bar': ButtonBar,
    'sl-form': Form,
    'sl-form-field': FormField,
    'sl-radio': Radio,
    'sl-radio-group': RadioGroup,
  };

  private get _form(): Form | null {
    return this.renderRoot.querySelector('sl-form');
  }

  private _onValidate(event: Event): void {
    const radioGroup = event.target as RadioGroup<string>;

    if (radioGroup.required && !radioGroup.value) {
      radioGroup.setCustomValidity('Please select an option.');
      return;
    }

    radioGroup.setCustomValidity(
      radioGroup.value === '2' ? '' : 'Pick the second option',
    );
  }

  private _reportValidity(): void {
    if (this._form?.reportValidity()) {
      window.open('about:blank', '_blank', 'noopener,noreferrer');
    }
  }

  override render(): TemplateResult {
    return html`
      <sl-form>
        <sl-form-field
          label="Active"
          hint="This story has both builtin validation (required) and custom validation. You need to check the second option to make the field valid."
        >
          <sl-radio-group @sl-validate=${this._onValidate} required>
            <sl-radio value="1">One</sl-radio>
            <sl-radio value="2">Two</sl-radio>
          </sl-radio-group>
        </sl-form-field>

        <sl-button-bar>
          <sl-button variant="primary" @click=${this._reportValidity}
            >Submit</sl-button
          >
        </sl-button-bar>

        <sl-form-field
          label="Disabled"
          hint="This radio group is disabled; no interaction is possible."
        >
          <sl-radio-group disabled>
            <sl-radio value="4">Four</sl-radio>
            <sl-radio value="5">Five</sl-radio>
          </sl-radio-group>
        </sl-form-field>
      </sl-form>
    `;
  }
}

// apps/vue-demo/src/components/sl-radio-group/sl-radio-group.vue
<template>
  <sl-form ref="formEl">
    <sl-form-field
      label="Active"
      hint="This story has both builtin validation (required) and custom validation. You need to check the second option to make the field valid."
    >
      <sl-radio-group @sl-validate="handleValidate" :required="true">
        <sl-radio value="1">One</sl-radio>
        <sl-radio value="2">Two</sl-radio>
      </sl-radio-group>
    </sl-form-field>

    <sl-button-bar>
      <sl-button variant="primary" @click="reportValidity">Submit</sl-button>
    </sl-button-bar>

    <sl-form-field
      label="Disabled"
      hint="This radio group is disabled; no interaction is possible."
    >
      <sl-radio-group :disabled="true">
        <sl-radio value="4">Four</sl-radio>
        <sl-radio value="5">Five</sl-radio>
      </sl-radio-group>
    </sl-form-field>
  </sl-form>
</template>

<script setup lang="ts">
import { ref } from 'vue';
import type { Form } from '@sl-design-system/form';
import type { RadioGroup } from '@sl-design-system/radio-group';
import '@sl-design-system/form/register.js';
import '@sl-design-system/button/register.js';
import '@sl-design-system/button-bar/register.js';
import '@sl-design-system/radio-group/register.js';

const formEl = ref<Form | null>(null);

function handleValidate(event: Event) {
  const radioGroup = event.target as RadioGroup<string>;

  if (radioGroup.required && !radioGroup.value) {
    radioGroup.setCustomValidity('Please select an option.');
    return;
  }

  radioGroup.setCustomValidity(
    radioGroup.value === '2' ? '' : 'Pick the second option',
  );
}

function reportValidity() {
  if (formEl.value?.reportValidity()) {
    window.open('about:blank', '_blank', 'noopener,noreferrer');
  }
}
</script>
