// apps/vue-demo/src/components/sl-paginator/sl-paginator.vue
<template>
  <ul>
    <li v-for="item in visibleItems" :key="item.id">
      {{ item.name }}
    </li>
  </ul>
  <sl-paginator-status
    :page="page"
    :page-size="pageSize"
    :total-items="allItems.length"
    item-label="items"
  ></sl-paginator-status>
  <sl-paginator
    ref="paginatorRef"
    :page="page"
    :page-size="pageSize"
    :total-items="allItems.length"
  ></sl-paginator>
  <sl-paginator-page-size
    ref="pageSizeRef"
    :page-size="pageSize"
    item-label="Items"
  ></sl-paginator-page-size>
</template>

<script setup lang="ts">
import { computed, onMounted, onUnmounted, ref } from 'vue';
import {
  Paginator,
  PaginatorPageSize,
  PaginatorStatus,
} from '@sl-design-system/paginator';

if (!customElements.get('sl-paginator'))
  customElements.define('sl-paginator', Paginator);
if (!customElements.get('sl-paginator-page-size'))
  customElements.define('sl-paginator-page-size', PaginatorPageSize);
if (!customElements.get('sl-paginator-status'))
  customElements.define('sl-paginator-status', PaginatorStatus);

import {
  ALL_ITEMS,
  type Item,
} from '../../../../../shared/utils/paginator-items.js';

const allItems: Item[] = ALL_ITEMS;

const page = ref(0);
const pageSize = ref(5);

const visibleItems = computed(() =>
  allItems.slice(
    page.value * pageSize.value,
    page.value * pageSize.value + pageSize.value,
  ),
);

const paginatorRef = ref<Paginator | null>(null);
const pageSizeRef = ref<PaginatorPageSize | null>(null);

function onPageChange(e: Event) {
  page.value = (e as CustomEvent<number>).detail;
}

function onPageSizeChange(e: Event) {
  pageSize.value = (e as CustomEvent<number>).detail;
  page.value = 0;
}

onMounted(() => {
  pageSizeRef.value?.pageSizes = [5, 10];
  paginatorRef.value?.addEventListener('sl-page-change', onPageChange);
  pageSizeRef.value?.addEventListener('sl-page-size-change', onPageSizeChange);
});

onUnmounted(() => {
  paginatorRef.value?.removeEventListener('sl-page-change', onPageChange);
  pageSizeRef.value?.removeEventListener(
    'sl-page-size-change',
    onPageSizeChange,
  );
});
</script>

// apps/angular-demo/src/app/components/sl-paginator/sl-paginator.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
  PaginatorComponent,
  PaginatorPageSizeComponent,
  PaginatorStatusComponent,
} from '@sl-design-system/angular/paginator';
import {
  ALL_ITEMS,
  type Item,
} from '../../../../../../shared/utils/paginator-items';

@Component({
  selector: 'app-paginator-page',
  templateUrl: './sl-paginator.component.html',
  imports: [
    PaginatorComponent,
    PaginatorPageSizeComponent,
    PaginatorStatusComponent,
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class PaginatorPageComponent {
  allItems: Item[] = ALL_ITEMS;

  page = 0;
  pageSize = 5;
  pageSizes = [5, 10];

  get visibleItems(): Item[] {
    const start = this.page * this.pageSize;
    return this.allItems.slice(start, start + this.pageSize);
  }

  onPageChange(event: CustomEvent<number>): void {
    this.page = event.detail;
  }

  onPageSizeChange(event: CustomEvent<number>): void {
    this.pageSize = event.detail;
    this.page = 0;
  }
}

<ul>
  @for (item of visibleItems; track item.id) {
    <li>{{ item.name }}</li>
  }
</ul>
<sl-paginator-status
  [page]="page"
  [pageSize]="pageSize"
  [totalItems]="allItems.length"
  itemLabel="items"
></sl-paginator-status>
<sl-paginator
  [page]="page"
  [pageSize]="pageSize"
  [totalItems]="allItems.length"
  (slPageChange)="onPageChange($event)"
></sl-paginator>
<sl-paginator-page-size
  [pageSize]="pageSize"
  [pageSizes]="pageSizes"
  itemLabel="Items"
  (slPageSizeChange)="onPageSizeChange($event)"
></sl-paginator-page-size>
