// apps/lit-demo/src/components/sl-paginator/sl-paginator.ts
import { html, LitElement, TemplateResult } from 'lit';
import { state } from 'lit/decorators.js';
import {
  ScopedElementsMixin,
  type ScopedElementsMap,
} from '@open-wc/scoped-elements/lit-element.js';
import {
  Paginator,
  PaginatorPageSize,
  PaginatorStatus,
} from '@sl-design-system/paginator';
import {
  ALL_ITEMS,
  type Item,
} from '../../../../../shared/utils/paginator-items.js';
import styles from './sl-paginator.scss.js';

export class PaginatorPage extends ScopedElementsMixin(LitElement) {
  static scopedElements: ScopedElementsMap = {
    'sl-paginator': Paginator,
    'sl-paginator-page-size': PaginatorPageSize,
    'sl-paginator-status': PaginatorStatus,
  };

  static override styles = styles;

  @state() private _page = 0;
  @state() private _pageSize = 5;

  private get _visibleItems(): Item[] {
    const start = this._page * this._pageSize;
    return ALL_ITEMS.slice(start, start + this._pageSize);
  }

  private _onPageChange(event: CustomEvent<number>): void {
    this._page = event.detail;
  }

  private _onPageSizeChange(event: CustomEvent<number>): void {
    this._pageSize = event.detail;
    this._page = 0;
  }

  override render(): TemplateResult {
    return html`
      <ul>
        ${this._visibleItems.map((item) => html`<li>${item.name}</li>`)}
      </ul>
      <sl-paginator-status
        .page=${this._page}
        .pageSize=${this._pageSize}
        .totalItems=${ALL_ITEMS.length}
        itemLabel="items"
      ></sl-paginator-status>
      <div class="paginator-wrapper">
        <sl-paginator
          .page=${this._page}
          .pageSize=${this._pageSize}
          .totalItems=${ALL_ITEMS.length}
          @sl-page-change=${this._onPageChange}
        ></sl-paginator>
      </div>
      <sl-paginator-page-size
        .pageSize=${this._pageSize}
        .pageSizes=${[5, 10]}
        itemLabel="Items"
        @sl-page-size-change=${this._onPageSizeChange}
      ></sl-paginator-page-size>
    `;
  }
}

// apps/angular-demo/src/app/components/sl-paginator/sl-paginator.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import {
  PaginatorComponent,
  PaginatorPageSizeComponent,
  PaginatorStatusComponent,
} from '@sl-design-system/angular/paginator';
import {
  ALL_ITEMS,
  type Item,
} from '../../../../../../shared/utils/paginator-items';

@Component({
  selector: 'app-paginator-page',
  templateUrl: './sl-paginator.component.html',
  styleUrls: ['./sl-paginator.component.scss'],
  imports: [
    PaginatorComponent,
    PaginatorPageSizeComponent,
    PaginatorStatusComponent,
  ],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class PaginatorPageComponent {
  allItems: Item[] = ALL_ITEMS;

  page = 0;
  pageSize = 5;
  pageSizes = [5, 10];

  get visibleItems(): Item[] {
    const start = this.page * this.pageSize;
    return this.allItems.slice(start, start + this.pageSize);
  }

  onPageChange(event: CustomEvent<number>): void {
    this.page = event.detail;
  }

  onPageSizeChange(event: CustomEvent<number>): void {
    this.pageSize = event.detail;
    this.page = 0;
  }
}

<ul>
  @for (item of visibleItems; track item.id) {
    <li>{{ item.name }}</li>
  }
</ul>
<sl-paginator-status
  [page]="page"
  [pageSize]="pageSize"
  [totalItems]="allItems.length"
  itemLabel="items"
></sl-paginator-status>
<sl-paginator
  [page]="page"
  [pageSize]="pageSize"
  [totalItems]="allItems.length"
  (slPageChange)="onPageChange($event)"
></sl-paginator>
<sl-paginator-page-size
  [pageSize]="pageSize"
  [pageSizes]="pageSizes"
  itemLabel="Items"
  (slPageSizeChange)="onPageSizeChange($event)"
></sl-paginator-page-size>
