// apps/svelte-demo/src/components/sl-tooltip/sl-tooltip.svelte
<script lang="ts">
  import '@sl-design-system/button/register.js';
  import '@sl-design-system/tooltip/register.js';
</script>

<div class="tooltip-example">
  <sl-button aria-describedby="tooltip" variant="primary">Button</sl-button>
  <sl-tooltip id="tooltip" position="top">This is the tooltip message</sl-tooltip>
</div>

// apps/angular-demo/src/app/components/sl-tooltip/sl-tooltip.component.ts
import { Component } from '@angular/core';
import { ButtonComponent } from '@sl-design-system/angular/button';
import { TooltipComponent } from '@sl-design-system/angular/tooltip';

@Component({
  selector: 'app-tooltip-page',
  templateUrl: './sl-tooltip.component.html',
  styleUrls: ['./sl-tooltip.component.scss'],
  imports: [ButtonComponent, TooltipComponent],
})
export class TooltipPageComponent {}

<div class="tooltip-example">
  <sl-button aria-describedby="tooltip" variant="primary">Button</sl-button>
  <sl-tooltip id="tooltip" position="top"
    >This is the tooltip message</sl-tooltip
  >
</div>
