// apps/vue-demo/src/components/sl-popover/sl-popover.vue
<template>
  <sl-button id="popover-trigger" @click="togglePopover" variant="primary">Toggle Popover</sl-button>
  <sl-popover anchor="popover-trigger" position="bottom">I'm a popover example with <sl-button variant="primary" @click="openBlankPage">Action</sl-button></sl-popover>
</template>

<script setup lang="ts">
import '@sl-design-system/button/register.js';
import '@sl-design-system/popover/register.js';

const togglePopover = () => {
  const popover = document.querySelector('sl-popover');
  popover?.togglePopover();
};

const openBlankPage = () => {
  window.open('about:blank', '_blank', 'noopener,noreferrer');
};
</script>

// apps/angular-demo/src/app/components/sl-popover/sl-popover.component.ts
import { Component, CUSTOM_ELEMENTS_SCHEMA } from '@angular/core';
import { ButtonComponent } from '@sl-design-system/angular/button';
import '@sl-design-system/popover/register.js';

@Component({
  selector: 'app-popover-page',
  templateUrl: './sl-popover.component.html',
  imports: [ButtonComponent],
  schemas: [CUSTOM_ELEMENTS_SCHEMA],
})
export class PopoverPageComponent {
  togglePopover(): void {
    const popover = document.querySelector('sl-popover') as HTMLElement | null;
    (popover as any)?.togglePopover();
  }
  openBlankPage() {
    window.open('about:blank', '_blank', 'noopener,noreferrer');
  }
}

<sl-button id="popover-trigger" (click)="togglePopover()" variant="primary">Toggle Popover</sl-button>
<sl-popover anchor="popover-trigger" position="bottom">I'm a popover example with <sl-button variant="primary" (click)="openBlankPage()">Action</sl-button></sl-popover>
