// apps/vue-demo/src/components/sl-menu/sl-menu.vue
<template>
  <sl-menu-button>
    <span slot="button">Menu</span>
    <sl-menu-item @click="openBlankPage">Test 1</sl-menu-item>
    <sl-menu-item>
      Test 2
      <sl-menu slot="submenu">
        <sl-menu-item @click="openBlankPage">Test 3</sl-menu-item>
      </sl-menu>
    </sl-menu-item>
    <sl-menu-item aria-disabled="true" @click="openBlankPage"
      >Test 4</sl-menu-item
    >
  </sl-menu-button>
</template>

<script setup lang="ts">
const openBlankPage = () => {
  window.open('about:blank', '_blank', 'noopener,noreferrer');
};
</script>

// apps/svelte-demo/src/components/sl-menu/sl-menu.svelte
<script lang="ts">
  function openBlankPage() {
    window.open('about:blank', '_blank', 'noopener,noreferrer');
  }

  function directClick(node: HTMLElement) {
    node.addEventListener('click', openBlankPage);
    return { destroy: () => node.removeEventListener('click', openBlankPage) };
  }
</script>

<!-- svelte-ignore a11y_click_events_have_key_events a11y_no_static_element_interactions -->
<sl-menu-button>
  <span slot="button">Menu</span>
  <sl-menu-item onclick={openBlankPage}>Test 1</sl-menu-item>
  <sl-menu-item>
    Test 2
    <sl-menu slot="submenu">
      <sl-menu-item use:directClick>Test 3</sl-menu-item>
    </sl-menu>
  </sl-menu-item>
  <sl-menu-item aria-disabled="true" onclick={openBlankPage}>Test 4</sl-menu-item>
</sl-menu-button>
