// apps/vue-demo/src/components/sl-tag/sl-tag.vue
<template>
  <sl-tag-list class="tags" aria-label="Subjects">
    <sl-tag removable="true">Mathematics</sl-tag>
    <sl-tag removable="true">Physics</sl-tag>
    <sl-tag :disabled="true" removable="true">Chemistry</sl-tag>
  </sl-tag-list>
</template>

<script setup lang="ts">
import '@sl-design-system/tag/register.js';
</script>

// apps/lit-demo/src/components/sl-tag/sl-tag.ts
import { html, LitElement, TemplateResult } from 'lit';
import {
  ScopedElementsMixin,
  type ScopedElementsMap,
} from '@open-wc/scoped-elements/lit-element.js';
import { Tag } from '@sl-design-system/tag';
import { TagList } from '@sl-design-system/tag';

export class TagPage extends ScopedElementsMixin(LitElement) {
  static scopedElements: ScopedElementsMap = {
    'sl-tag': Tag,
    'sl-tag-list': TagList,
  };

  override render(): TemplateResult {
    return html`
      <sl-tag-list class="tags" aria-label="Subjects">
        <sl-tag removable>Mathematics</sl-tag>
        <sl-tag removable>Physics</sl-tag>
        <sl-tag ?disabled=${true} removable>Chemistry</sl-tag>
      </sl-tag-list>
    `;
  }
}
