// apps/angular-demo/src/app/components/sl-avatar/sl-avatar.component.ts
import { Component } from '@angular/core';
import { AvatarComponent } from '@sl-design-system/angular/avatar';

@Component({
  selector: 'app-avatar-page',
  templateUrl: './sl-avatar.component.html',
  styleUrls: ['./sl-avatar.component.scss'],
  imports: [AvatarComponent],
})
export class AvatarPageComponent {}

<sl-avatar displayName="Jan Janssen" href="about:blank" picture-url="https://images.unsplash.com/photo-1586622992874-27d98f198139?q=80&w=400&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" size="lg">
  30 May
</sl-avatar>

// apps/vue-demo/src/components/sl-avatar/sl-avatar.vue
<template>
  <sl-avatar display-name="Jan Janssen" href="about:blank" picture-url="https://images.unsplash.com/photo-1586622992874-27d98f198139?q=80&w=400&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" size="lg">
    30 May
  </sl-avatar>
</template>

<script setup lang="ts">
import '@sl-design-system/avatar/register.js';
</script>
