// apps/lit-demo/src/components/sl-avatar/sl-avatar.ts
import { html, LitElement, TemplateResult } from 'lit';
import {
  ScopedElementsMixin,
  type ScopedElementsMap,
} from '@open-wc/scoped-elements/lit-element.js';
import { Avatar } from '@sl-design-system/avatar';

export class AvatarPage extends ScopedElementsMixin(LitElement) {
  static scopedElements: ScopedElementsMap = {
    'sl-avatar': Avatar,
  };

  override render(): TemplateResult {
    return html`
      <sl-avatar
        display-name="Jan Janssen"
        href="about:blank"
        picture-url="https://images.unsplash.com/photo-1586622992874-27d98f198139?q=80&w=400&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D"
        size="lg"
      >
        30 May
      </sl-avatar>
    `;
  }
}

// apps/vue-demo/src/components/sl-avatar/sl-avatar.vue
<template>
  <sl-avatar display-name="Jan Janssen" href="about:blank" picture-url="https://images.unsplash.com/photo-1586622992874-27d98f198139?q=80&w=400&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D" size="lg">
    30 May
  </sl-avatar>
</template>

<script setup lang="ts">
import '@sl-design-system/avatar/register.js';
</script>
