// apps/lit-demo/src/components/sl-combobox/sl-combobox.ts
import { html, LitElement, TemplateResult } from 'lit';
import {
  ScopedElementsMixin,
  type ScopedElementsMap,
} from '@open-wc/scoped-elements/lit-element.js';
import { Combobox } from '@sl-design-system/combobox';
import { Listbox, Option } from '@sl-design-system/listbox';

export class ComboboxPage extends ScopedElementsMixin(LitElement) {
  static scopedElements: ScopedElementsMap = {
    'sl-combobox': Combobox,
    'sl-listbox': Listbox,
    'sl-option': Option,
  };

  override render(): TemplateResult {
    return html`
      <sl-combobox multiple aria-label="Label">
        <sl-listbox>
          <sl-option value="0">Test 1</sl-option>
          <sl-option value="1">Test 2</sl-option>
        </sl-listbox>
      </sl-combobox>
    `;
  }
}

// apps/vue-demo/src/components/sl-combobox/sl-combobox.vue
<template>
  <sl-combobox :multiple="true" aria-label="Label">
    <sl-listbox>
      <sl-option value="0">Test 1</sl-option>
      <sl-option value="1">Test 2</sl-option>
    </sl-listbox>
  </sl-combobox>
</template>

<script setup lang="ts">
import '@sl-design-system/combobox/register.js';
</script>
